apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    mayank: trainingpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /code
    server: 146.148.52.144
