apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - max: 
      cpu: '1'
      memory: 1000Mi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container
  - max:
      cpu: '1'
      memory: 2000Mi
    min:
      cpu: 20m
      memory: 20Mi
    type: Pod
